### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.gnome.Brasero#12]
If possible, please consider verifying this Flatpak.

Here is more info about verified apps: https://flathub.org/about

**Comment by applemayexist** [comment]
I don't think that that's something I'm able to do. I'm not a developer of GNOME or Brasero, which I think is exactly the distinction that verification is supposed to provide.

**Comment by AsciiWolf** [comment]
Fair point. Feel free to close this issue. Or you can try inviting the actual developer to co-maintain this Flatpak. :)

**Comment by applemayexist** [comment]
I opened [an issue](https://gitlab.gnome.org/GNOME/brasero/-/issues/368) on Brasero's issue tracker before submitting this flatpak, but Brasero doesn't have any active maintainers (who uses DVDs anymore?), so there was no interest.

**Comment by AsciiWolf** [comment]
@applemayexist The Brasero Flatpak is still unverified and there is nothing related in the ticket you linked. This ticket should be re-opened or you should submit a new upstream ticket. Thanks!
